name: Train Model CI

on:
  push:
    paths:
      - 'MLProject/**'
      - '.github/workflows/train_model.yml'
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v3

      - name: 🧪 Set Up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: ml-env
          environment-file: MLProject/conda.yaml
          auto-activate-base: false
          use-only-tar-bz2: true

      - name: 🚀 Run MLflow Project (tanpa env baru)
        shell: bash -l {0}
        env:
          MLFLOW_TRACKING_URI: https://dagshub.com/gimnastiarhrn/Membangun_Model.mlflow
          MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
        run: |
          conda activate ml-env
          cd MLProject
          echo "👉 Menjalankan MLflow tanpa conda env baru..."
          mlflow run . --env-manager=local -P data_dir=processed

      - name: 📦 Upload Trained Model Artifact
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: MLProject/model/model.pkl
