name: Train Model CI

on:
  push:
    paths:
      - 'MLProject/**'
      - '.github/workflows/train_model.yml'
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v3

      - name: 🧪 Set Up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: ml-env
          environment-file: MLProject/conda.yaml
          auto-activate-base: false
          use-only-tar-bz2: true

      - name: 🚀 Activate Conda and Run MLflow Project
        shell: bash -l {0}
        env:
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          conda activate ml-env
          cd MLProject
          mlflow run .

      - name: 📦 Upload Trained Model Artifact
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: MLProject/model/model.pkl
